### ISSUE TITLE
Crash at [super viewDidLoad] - Xcode 8

### ISSUE THREAD

**Issue by tomqz** [bigfish24/ABFRealmSearchViewController#13]
Hi. I've updated Xcode to 8.0. I have a view, that is subclassing ABFRealmSearchViewController. When i want to open this view I'm getting a crash in viewDidLoad method at [super viewDidLoad];.

I've checked where the problem is, it crashes is in ABFRealmSearchViewController.m at line self.viewLoaded = YES; in viewDidLoad method.

Any ideas what's wrong?

**Comment by chodges** [comment]
Yeah that's a property for the parent ViewController and Swift is now being stricter and telling you nope you can't use that because its already defined somewhere else as part of its class (ViewController).

Bottom line is if you're thinking about ever migrating to Swift 3 you probably don't want to use this component because there are about 28 issues with it and so needs a major upgrade or rewrite.

**Comment by tomqz** [comment]
I don't know if my solution is ok, but i renamed your property to "isViewLoaded" and it works :) I've tested it and it seems that everything is ok ;) (My project is in Objc)

**Comment by chodges** [comment]
Yes Obj-C is fine but Swift does not work correctly.

**Comment by shravanteegala** [comment]
How it Add isViewLoaded property . can you give detail.

**Comment by tomqz** [comment]
If you're project is ObjC, You have to rename the property BOOL viewLoaded - to isViewLoaded and that's all.

**Comment by shravanteegala** [comment]
Thank you, its Working.

**Comment by bigfish24** [comment]
The Swift version is updated to Swift 3 here: https://github.com/bigfish24/ABFRealmSearchViewController/releases/tag/v2.2.1 and I fixed the issue with `viewLoaded`.
